services:
  db:
    image: postgres:16-alpine
    container_name: postgres_local
    restart: unless-stopped
    environment:
      POSTGRES_USER: loky
      POSTGRES_PASSWORD: loky
      POSTGRES_DB: IngSoft
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_local
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db